### ISSUE TITLE
Node.js domain module fully deprecated in Node.js v9.2.0

### ISSUE THREAD

**Issue by Aglezabad** [bevry/progressbar#5]
Related with docpad/docpad#1068, I've discovered that the failure caused in Docpad issue is due to fully deprecation of domains module. 
I will try to send a PR with a fix for that.

Reference: https://nodejs.org/en/docs/guides/domain-postmortem/

**Comment by balupton** [comment]
This module has been deprecated in favour of https://github.com/bevry/progress-title
